
;	case	pass_nb
;=4
;	ds.b		78*512
;	incbin		block880.bin
;	endcase
	filename	a1chaos.cas,d:\main\chaos\data.pak\
	filename	shop1.ins,d:\main\chaos\data.pak\
	filename	lev3.ins,d:\main\chaos\data.pak\
	filename	lev1.ins,d:\main\chaos\data.pak\
	filename	lev4.ins,d:\main\chaos\data.pak\
	filename	lev2.ins,d:\main\chaos\data.pak\
	filename	lev1bak.bin,d:\main\chaos\data.pak\
	filename	lev3bak.bin,d:\main\chaos\data.pak\
	filename	lev2bak.bin,d:\main\chaos\data.pak\
	filename	am_dead.bin,d:\main\chaos\data.pak\
	filename	thumper.bin,d:\main\chaos\data.pak\
	filename	compost.bin,d:\main\chaos\data.pak\
	filename	lev4bak.bin,d:\main\chaos\data.pak\
	filename	navvie.bin,d:\main\chaos\data.pak\
	filename	lev6bak.bin,d:\main\chaos\data.pak\
	filename	steamjet.bin,d:\main\chaos\data.pak\
	filename	barongun.bin,d:\main\chaos\data.pak\
	filename	dhturret.bin,d:\main\chaos\data.pak\
	filename	engyball.bin,d:\main\chaos\data.pak\
	filename	blob.bin,d:\main\chaos\data.pak\
	filename	am_equip.bin,d:\main\chaos\data.pak\
	case	pass_nb
=4
	incbin		f:\main\chaos\data\block882.bin
	endcase
	filename	thug.bin,d:\main\chaos\data.pak\
	filename	mercenry.bin,d:\main\chaos\data.pak\
	filename	gentlman.bin,d:\main\chaos\data.pak\
	filename	brigand.bin,d:\main\chaos\data.pak\
	filename	preacher.bin,d:\main\chaos\data.pak\
	filename	frogger.bin,d:\main\chaos\data.pak\
	filename	am_outr1.bin,d:\main\chaos\data.pak\
	filename	lobber.bin,d:\main\chaos\data.pak\
	filename	beast.bin,d:\main\chaos\data.pak\
	filename	misslink.bin,d:\main\chaos\data.pak\
	filename	kangaroo.bin,d:\main\chaos\data.pak\
	filename	sewer.bin,d:\main\chaos\data.pak\
	filename	halftrak.bin,d:\main\chaos\data.pak\
	filename	rockman.bin,d:\main\chaos\data.pak\
	filename	guard.bin,d:\main\chaos\data.pak\
	filename	lev5bak.bin,d:\main\chaos\data.pak\
	filename	lizman.bin,d:\main\chaos\data.pak\
	filename	b1chaos.cas,d:\main\chaos\data.pak\
	filename	c1chaos.cas,d:\main\chaos\data.pak\
	filename	hand.bin,d:\main\chaos\data.pak\
	filename	h1chaos.cas,d:\main\chaos\data.pak\
	filename	m1chaos.cas,d:\main\chaos\data.pak\
	filename	e1chaos.cas,d:\main\chaos\data.pak\
	filename	g1chaos.cas,d:\main\chaos\data.pak\
	filename	j1chaos.cas,d:\main\chaos\data.pak\
	filename	n1chaos.cas,d:\main\chaos\data.pak\
	filename	am_outr0.bin,d:\main\chaos\data.pak\
	filename	i1chaos.cas,d:\main\chaos\data.pak\
	filename	l1chaos.cas,d:\main\chaos\data.pak\
	filename	d1chaos.cas,d:\main\chaos\data.pak\
	filename	emplacmt.bin,d:\main\chaos\data.pak\
	filename	p1chaos.cas,d:\main\chaos\data.pak\
	filename	am_outr2.bin,d:\main\chaos\data.pak\
	filename	k1chaos.cas,d:\main\chaos\data.pak\
	filename	robot.bin,d:\main\chaos\data.pak\
	filename	f1chaos.cas,d:\main\chaos\data.pak\
	filename	o1chaos.cas,d:\main\chaos\data.pak\
	filename	dustdevl.bin,d:\main\chaos\data.pak\
	filename	mace.bin,d:\main\chaos\data.pak\
	filename	gyro_big.bin,d:\main\chaos\data.pak\
	filename	thebaron.bin,d:\main\chaos\data.pak\
	filename	fire_man.bin,d:\main\chaos\data.pak\
	filename	shop1.sng,d:\main\chaos\data.pak\
	filename	beetle.bin,d:\main\chaos\data.pak\
	filename	rat.bin,d:\main\chaos\data.pak\
	filename	mechanic.bin,d:\main\chaos\data.pak\
	filename	slug.bin,d:\main\chaos\data.pak\
	filename	spider.bin,d:\main\chaos\data.pak\
	filename	stonewat.bin,d:\main\chaos\data.pak\
	filename	am_tapes.bin,d:\main\chaos\data.pak\
	filename	cocoon.bin,d:\main\chaos\data.pak\
	filename	emplgun.bin,d:\main\chaos\data.pak\
	filename	revdome.bin,d:\main\chaos\data.pak\

