#include "iff/compiler.h"
struct Region { long dummy; };
struct VSprite { long dummy; };
struct collTable { long dummy; };
struct TimeVal { long dummy; };
#include "exec/types.h"
#include "exec/nodes.h"
#include "exec/lists.h"
#include "exec/libraries.h"
#include "exec/ports.h"
#include "exec/tasks.h"
#include "exec/devices.h"
#include "exec/interrupts.h"
#include "exec/io.h"
#include "exec/memory.h"
#include "exec/alerts.h"
#include "graphics/gfx.h"
#include "graphics/clip.h"
#include "graphics/rastport.h"
#include "graphics/view.h"
#include "graphics/gfxbase.h"
#include "graphics/gfxmacros.h"
#include "graphics/layers.h"
#include "graphics/text.h"
#include "graphics/sprite.h"
#include "devices/timer.h"
#include "devices/inputevent.h"
#include "devices/keymap.h"
#include "intuition/intuition.h"
