// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Apr 03 11:24:46 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MAIN_H
#define MAIN_H


// begin wxGlade: ::extracode
// end wxGlade

class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxListBox* list_box_1;
    wxButton* button_1;
    wxButton* button_2;
    wxListBox* list_box_2;
    wxButton* button_3;
    wxButton* button_4;
    wxMenuBar* frame_1_menubar;
    wxStatusBar* frame_1_statusbar;
    // end wxGlade
    
    // event handlers
    void OnButtonClear(wxCommandEvent& event);
    void OnButtonAdd(wxCommandEvent& event);
    void OnButtonRemove(wxCommandEvent& event);
    void OnButtonProcess(wxCommandEvent& event);

    void OnMenuQuit(wxCommandEvent& event);
    void OnMenuAbout(wxCommandEvent& event);

    void OnWorklist(wxCommandEvent& event);
    void OnFilelist(wxCommandEvent& event);

private:

    // helper protos
    void UpdateFileList(char *);
    
    char path[1024];

    // any class wishing to process wxWidgets events must use this macro
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class

#endif // MAIN_H
