//units
#include "units/UnitClass.h"
#include "units/GroundUnit.h"
#include "units/TrackedUnit.h"
#include "units/AirUnit.h"
#include "units/Carryall.h"
#include "units/Frigate.h"
#include "units/HarvesterClass.h"
#include "units/LauncherClass.h"
#include "units/DeviatorClass.h"
#include "units/DevastatorClass.h"
#include "units/InfantryClass.h"
#include "units/MCVClass.h"
#include "units/Ornithopter.h"
#include "units/QuadClass.h"
#include "units/Saboteur.h"
#include "units/SandWorm.h"
#include "units/SonicTankClass.h"
#include "units/TankClass.h"
#include "units/SiegeTankClass.h"
#include "units/TrikeClass.h"
#include "units/RaiderClass.h"
#include "units/TrooperClass.h"
#include "units/SardaukarClass.h"
#include "units/FremenClass.h"

//structures
#include "structures/StructureClass.h"
#include "structures/BuilderClass.h"
#include "structures/BarracksClass.h"
#include "structures/ConstructionYardClass.h"
#include "structures/GunTurretClass.h"
#include "structures/HeavyFactoryClass.h"
#include "structures/HighTechFactoryClass.h"
#include "structures/IXClass.h"
#include "structures/LightFactoryClass.h"
#include "structures/PalaceClass.h"
#include "structures/RadarClass.h"
#include "structures/RefineryClass.h"
#include "structures/RepairYardClass.h"
#include "structures/RocketTurretClass.h"
#include "structures/SiloClass.h"
#include "structures/StarPortClass.h"
#include "structures/WallClass.h"
#include "structures/WindTrapClass.h"
#include "structures/WORClass.h"

