	filename	ramer,f:\main\chaos\data\
	filename	achaos,d:\main\chaos\data.pak\
	filename	am_back.bin,d:\main\chaos\data.pak\
	filename	am_itext.bin,d:\main\chaos\data.pak\
	filename	sngarc.bin,d:\main\chaos\data.pak\
	filename	static.bin,d:\main\chaos\data.pak\
	filename	levsdat.bin,d:\main\chaos\data.pak\
	filename	shop.ins,d:\main\chaos\data.pak\
	filename	sngarc2.bin,d:\main\chaos\data.pak\
	case	pass_nb
=4
	ds.b		13*512
	incbin		f:\main\chaos\data\block881.bin
	endcase
	filename	title.mod,d:\main\chaos\data.pak\
	filename	lev9.ins,d:\main\chaos\data.pak\
	filename	am_font.bin,d:\main\chaos\data.pak\
